{{- if .Values.persistence.artifacts.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "made.fullname" . }}-artifacts
  labels:
    {{- include "made.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.artifacts.size | quote }}
  {{- with .Values.persistence.artifacts.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
