//! Use cases.
//!
//! Each use case is a struct, constructor-injected with the ports it
//! needs, and exposes a single `execute` method. This keeps
//! responsibilities narrow (SRP) and dependencies explicit (DIP).

#[cfg(test)]
mod ceremony_event_subscriber_tests;
#[cfg(test)]
mod ceremony_test_support;
#[cfg(test)]
mod start_ceremony_step_role_tests;

mod apply_ceremony_transition_input;
mod apply_ceremony_transition_use_case;
mod approve_ceremony_guard_input;
mod approve_ceremony_guard_use_case;
mod assert_ceremony_reason_input;
mod assert_ceremony_reason_use_case;
mod bind_ceremony_participants_input;
mod bind_ceremony_participants_use_case;
mod ceremony_definition_source;
mod ceremony_design_document;
mod ceremony_design_exit_guard;
mod ceremony_design_final_approval;
mod ceremony_design_group;
mod ceremony_design_group_repeat;
mod ceremony_design_group_repeat_until;
mod ceremony_design_group_step;
mod ceremony_design_join;
mod ceremony_design_output_field_guard;
mod ceremony_design_participant;
mod ceremony_design_repeat;
mod ceremony_design_stage;
mod ceremony_design_stage_entry;
mod ceremony_design_step_repeat_exhausted_guard;
mod ceremony_draft_element_count;
mod ceremony_draft_summary;
mod ceremony_draft_view;
mod ceremony_event_page;
mod ceremony_guard_view;
mod ceremony_instance_read;
mod ceremony_instance_view;
mod ceremony_journal_verdict;
mod ceremony_participant_capability;
mod ceremony_participant_descriptor;
mod ceremony_pattern_preset;
mod ceremony_report;
mod ceremony_report_binding;
mod ceremony_report_ids;
mod ceremony_step_trace;
mod ceremony_step_view;
mod ceremony_transition_view;
mod close_ceremony_intervention_input;
mod close_ceremony_intervention_use_case;
mod collect_ceremony_evidence_input;
mod collect_ceremony_evidence_use_case;
mod complete_ceremony_step_input;
mod complete_ceremony_step_use_case;
mod create_council;
mod create_council_input;
mod defer_ceremony_guard_input;
mod defer_ceremony_guard_use_case;
mod delete_council;
mod deliberate;
mod deliberate_output;
mod design_ceremony_use_case;
mod designed_ceremony;
mod diff_ceremony_definitions_use_case;
mod generate_ceremony_report_input;
mod generate_ceremony_report_use_case;
mod get_ceremony_definition;
mod get_ceremony_instance;
mod get_ceremony_transcript;
mod get_deliberation;
mod get_service_metrics_use_case;
mod get_service_status_use_case;
mod import_pre_stream_instances_use_case;
mod list_ceremony_definitions;
mod list_ceremony_instances;
mod list_councils;
mod mount_ceremony_definitions_output;
mod mount_ceremony_definitions_use_case;
mod orchestrate;
mod orchestrate_output;
mod pre_stream_import;
mod prepare_ceremony_participants_input;
mod prepare_ceremony_participants_use_case;
mod prepare_step_execution;
mod prepared_step_execution;
mod publish_ceremony_definition_use_case;
mod publish_ceremony_events_round;
mod publish_ceremony_events_use_case;
mod pull_ceremony_events_input;
mod pull_ceremony_events_output;
mod pull_ceremony_events_use_case;
mod read_ceremony_events_input;
mod read_ceremony_events_use_case;
mod read_whole_ceremony_events_use_case;
mod register_agent;
mod report_title;
mod request_ceremony_intervention_input;
mod request_ceremony_intervention_use_case;
mod resolve_ceremony_definition_use_case;
mod respond_to_ceremony_intervention_input;
mod respond_to_ceremony_intervention_use_case;
mod run_ceremony_input;
mod run_ceremony_output;
mod run_ceremony_step_input;
mod run_ceremony_step_output;
mod run_ceremony_step_use_case;
mod run_ceremony_use_case;
mod run_council_decision;
mod run_council_decision_input;
mod run_council_decision_output;
mod service_health;
mod service_metrics;
mod service_status;
mod start_ceremony_input;
mod start_ceremony_step_input;
mod start_ceremony_step_output;
mod start_ceremony_step_use_case;
mod start_ceremony_use_case;
mod start_published_ceremony_use_case;
mod step_role_resolution;
mod step_span;
mod unregister_agent;
mod verify_ceremony_journal_use_case;
mod winner_selection;

pub use apply_ceremony_transition_input::ApplyCeremonyTransitionInput;
pub use apply_ceremony_transition_use_case::ApplyCeremonyTransitionUseCase;
pub use approve_ceremony_guard_input::ApproveCeremonyGuardInput;
pub use approve_ceremony_guard_use_case::ApproveCeremonyGuardUseCase;
pub use assert_ceremony_reason_input::AssertCeremonyReasonInput;
pub use assert_ceremony_reason_use_case::AssertCeremonyReasonUseCase;
pub use bind_ceremony_participants_input::BindCeremonyParticipantsInput;
pub use bind_ceremony_participants_use_case::BindCeremonyParticipantsUseCase;
pub use ceremony_definition_source::CeremonyDefinitionSource;
pub use ceremony_design_document::CeremonyDesignDocument;
pub use ceremony_design_exit_guard::CeremonyDesignExitGuard;
pub use ceremony_design_final_approval::CeremonyDesignFinalApproval;
pub use ceremony_design_group::CeremonyDesignGroup;
pub use ceremony_design_group_repeat::CeremonyDesignGroupRepeat;
pub use ceremony_design_group_repeat_until::CeremonyDesignGroupRepeatUntil;
pub use ceremony_design_group_step::CeremonyDesignGroupStep;
pub use ceremony_design_join::CeremonyDesignJoin;
pub use ceremony_design_output_field_guard::CeremonyDesignOutputFieldGuard;
pub use ceremony_design_participant::CeremonyDesignParticipant;
pub use ceremony_design_repeat::CeremonyDesignRepeat;
pub use ceremony_design_stage::CeremonyDesignStage;
pub use ceremony_design_stage_entry::CeremonyDesignStageEntry;
pub use ceremony_design_step_repeat_exhausted_guard::CeremonyDesignStepRepeatExhaustedGuard;
pub use ceremony_draft_element_count::CeremonyDraftElementCount;
pub use ceremony_draft_summary::CeremonyDraftSummary;
pub use ceremony_draft_view::CeremonyDraftView;
pub use ceremony_event_page::CeremonyEventPage;
pub use ceremony_guard_view::CeremonyGuardView;
pub use ceremony_instance_read::CeremonyInstanceRead;
pub use ceremony_instance_view::CeremonyInstanceView;
pub use ceremony_journal_verdict::CeremonyJournalVerdict;
pub use ceremony_participant_capability::CeremonyParticipantCapability;
pub use ceremony_participant_descriptor::CeremonyParticipantDescriptor;
pub use ceremony_pattern_preset::CeremonyPatternPreset;
pub use ceremony_report::CeremonyReport;
pub use ceremony_report_binding::CeremonyReportBinding;
pub use ceremony_report_ids::CeremonyReportIds;
pub use ceremony_step_trace::CeremonyStepTrace;
pub use ceremony_step_view::CeremonyStepView;
pub use ceremony_transition_view::CeremonyTransitionView;
pub use close_ceremony_intervention_input::CloseCeremonyInterventionInput;
pub use close_ceremony_intervention_use_case::CloseCeremonyInterventionUseCase;
pub use collect_ceremony_evidence_input::CollectCeremonyEvidenceInput;
pub use collect_ceremony_evidence_use_case::CollectCeremonyEvidenceUseCase;
pub use complete_ceremony_step_input::CompleteCeremonyStepInput;
pub use complete_ceremony_step_use_case::CompleteCeremonyStepUseCase;
pub use create_council::CreateCouncilUseCase;
pub use create_council_input::CreateCouncilInput;
pub use defer_ceremony_guard_input::DeferCeremonyGuardInput;
pub use defer_ceremony_guard_use_case::DeferCeremonyGuardUseCase;
pub use delete_council::DeleteCouncilUseCase;
pub use deliberate::DeliberateUseCase;
pub use deliberate_output::DeliberateOutput;
pub use design_ceremony_use_case::DesignCeremonyUseCase;
pub use designed_ceremony::DesignedCeremony;
pub use diff_ceremony_definitions_use_case::DiffCeremonyDefinitionsUseCase;
pub use generate_ceremony_report_input::GenerateCeremonyReportInput;
pub use generate_ceremony_report_use_case::GenerateCeremonyReportUseCase;
pub use get_ceremony_definition::GetCeremonyDefinitionUseCase;
pub use get_ceremony_instance::GetCeremonyInstanceUseCase;
pub use get_ceremony_transcript::GetCeremonyTranscriptUseCase;
pub use get_deliberation::GetDeliberationUseCase;
pub use get_service_metrics_use_case::GetServiceMetricsUseCase;
pub use get_service_status_use_case::GetServiceStatusUseCase;
pub use import_pre_stream_instances_use_case::ImportPreStreamInstancesUseCase;
pub use list_ceremony_definitions::ListCeremonyDefinitionsUseCase;
pub use list_ceremony_instances::ListCeremonyInstancesUseCase;
pub use list_councils::ListCouncilsUseCase;
pub use mount_ceremony_definitions_output::MountCeremonyDefinitionsOutput;
pub use mount_ceremony_definitions_use_case::MountCeremonyDefinitionsUseCase;
pub use orchestrate::OrchestrateUseCase;
pub use orchestrate_output::OrchestrateOutput;
pub use pre_stream_import::PreStreamImport;
pub use prepare_ceremony_participants_input::PrepareCeremonyParticipantsInput;
pub use prepare_ceremony_participants_use_case::PrepareCeremonyParticipantsUseCase;
pub use prepare_step_execution::prepare_step_execution;
pub use prepared_step_execution::PreparedStepExecution;
pub use publish_ceremony_definition_use_case::PublishCeremonyDefinitionUseCase;
pub use publish_ceremony_events_round::PublishCeremonyEventsRound;
pub use publish_ceremony_events_use_case::PublishCeremonyEventsUseCase;
pub use pull_ceremony_events_input::PullCeremonyEventsInput;
pub use pull_ceremony_events_output::PullCeremonyEventsOutput;
pub use pull_ceremony_events_use_case::PullCeremonyEventsUseCase;
pub use read_ceremony_events_input::ReadCeremonyEventsInput;
pub use read_ceremony_events_use_case::ReadCeremonyEventsUseCase;
pub use read_whole_ceremony_events_use_case::ReadWholeCeremonyEventsUseCase;
pub use register_agent::RegisterAgentUseCase;
pub use report_title::ReportTitle;
pub use request_ceremony_intervention_input::RequestCeremonyInterventionInput;
pub use request_ceremony_intervention_use_case::RequestCeremonyInterventionUseCase;
pub use resolve_ceremony_definition_use_case::ResolveCeremonyDefinitionUseCase;
pub use respond_to_ceremony_intervention_input::RespondToCeremonyInterventionInput;
pub use respond_to_ceremony_intervention_use_case::RespondToCeremonyInterventionUseCase;
pub use run_ceremony_input::RunCeremonyInput;
pub use run_ceremony_output::RunCeremonyOutput;
pub use run_ceremony_step_input::RunCeremonyStepInput;
pub use run_ceremony_step_output::RunCeremonyStepOutput;
pub use run_ceremony_step_use_case::RunCeremonyStepUseCase;
pub use run_ceremony_use_case::RunCeremonyUseCase;
pub use run_council_decision::RunCouncilDecisionUseCase;
pub use run_council_decision_input::RunCouncilDecisionInput;
pub use run_council_decision_output::RunCouncilDecisionOutput;
pub use service_health::ServiceHealth;
pub use service_metrics::ServiceMetrics;
pub use service_status::ServiceStatus;
pub use start_ceremony_input::StartCeremonyInput;
pub use start_ceremony_step_input::StartCeremonyStepInput;
pub use start_ceremony_step_output::StartCeremonyStepOutput;
pub use start_ceremony_step_use_case::StartCeremonyStepUseCase;
pub use start_ceremony_use_case::StartCeremonyUseCase;
pub use start_published_ceremony_use_case::StartPublishedCeremonyUseCase;
pub use unregister_agent::UnregisterAgentUseCase;
pub use verify_ceremony_journal_use_case::VerifyCeremonyJournalUseCase;
