//! Which tools the embedded engine serves.
//!
//! One predicate, asked by the backend's `supports_tool` and by the
//! terminal `grant` command when it maps a tool profile to the actions
//! a person is about to allow. Its own file so the backend's dispatch
//! table and this list, which must agree, are each read whole.

use super::embedded_extension_dispatch;
use crate::protocol::{
    ACCEPT_CHILD_COMPLETION_TOOL, ADOPT_EXECUTION_RECEIPT_TOOL, APPLY_CEREMONY_TRANSITION_TOOL,
    APPROVE_CEREMONY_GUARD_TOOL, ASSERT_CEREMONY_REASON_TOOL, BIND_CEREMONY_PARTICIPANTS_TOOL,
    CANCEL_CEREMONY_TOOL, CLAIM_CEREMONY_STEP_TOOL, CLOSE_CEREMONY_INTERVENTION_TOOL,
    COLLECT_CEREMONY_EVIDENCE_TOOL, COMPLETE_CEREMONY_STEP_TOOL, COMPLETE_EXECUTION_RECEIPT_TOOL,
    DEFER_CEREMONY_GUARD_TOOL, DESIGN_CEREMONY_TOOL, DIFF_CEREMONY_DEFINITIONS_TOOL,
    ENFORCE_CEREMONY_DEADLINES_TOOL, EXPLAIN_CEREMONY_DRAFT_TOOL, GENERATE_CEREMONY_REPORT_TOOL,
    GET_CEREMONY_INSTANCE_TOOL, GET_CEREMONY_TRANSCRIPT_TOOL, GET_EXECUTION_RECEIPT_TOOL,
    GET_METRICS_TOOL, GET_STATUS_TOOL, INSPECT_CEREMONY_RESUME_TOOL,
    INSPECT_EXECUTION_RECOVERY_TOOL, LIST_CEREMONY_INSTANCES_TOOL, PAUSE_CEREMONY_TOOL,
    PREPARE_CEREMONY_CHILDREN_TOOL, PUBLISH_CEREMONY_DEFINITION_TOOL, PULL_CEREMONY_EVENTS_TOOL,
    READ_CEREMONY_EVENTS_TOOL, RECORD_CEREMONY_HOST_HANDOFF_TOOL, RECOVER_CEREMONY_CHILDREN_TOOL,
    RENEW_CEREMONY_STEP_LEASE_TOOL, REQUEST_CEREMONY_INTERVENTION_TOOL,
    RESPOND_TO_CEREMONY_INTERVENTION_TOOL, RESUME_CEREMONY_TOOL, RUN_CEREMONY_STEP_TOOL,
    RUN_CEREMONY_TOOL, SEARCH_CEREMONY_INSTANCES_TOOL, START_CEREMONY_TOOL,
    START_PUBLISHED_CEREMONY_TOOL, STREAM_CEREMONY_TOOL, VALIDATE_CEREMONY_DRAFT_TOOL,
    VERIFY_CEREMONY_JOURNAL_TOOL,
};

/// Whether the embedded engine serves `name`: every tool of the
/// catalog this backend has an arm for. A function rather than only a
/// method so that a command with no backend in hand (the terminal
/// `grant`, mapping a tool profile to actions) asks the same question.
#[must_use]
pub(crate) fn embedded_supports_tool(name: &str) -> bool {
    if embedded_extension_dispatch::handles(name) {
        return true;
    }
    matches!(
        name,
        RUN_CEREMONY_TOOL
            | START_CEREMONY_TOOL
            | RUN_CEREMONY_STEP_TOOL
            | PREPARE_CEREMONY_CHILDREN_TOOL
            | ACCEPT_CHILD_COMPLETION_TOOL
            | RECOVER_CEREMONY_CHILDREN_TOOL
            | CLAIM_CEREMONY_STEP_TOOL
            | RENEW_CEREMONY_STEP_LEASE_TOOL
            | COMPLETE_CEREMONY_STEP_TOOL
            | GET_EXECUTION_RECEIPT_TOOL
            | INSPECT_EXECUTION_RECOVERY_TOOL
            | COMPLETE_EXECUTION_RECEIPT_TOOL
            | ADOPT_EXECUTION_RECEIPT_TOOL
            | APPROVE_CEREMONY_GUARD_TOOL
            | DEFER_CEREMONY_GUARD_TOOL
            | APPLY_CEREMONY_TRANSITION_TOOL
            | PAUSE_CEREMONY_TOOL
            | RESUME_CEREMONY_TOOL
            | RECORD_CEREMONY_HOST_HANDOFF_TOOL
            | INSPECT_CEREMONY_RESUME_TOOL
            | CANCEL_CEREMONY_TOOL
            | ENFORCE_CEREMONY_DEADLINES_TOOL
            | GET_CEREMONY_INSTANCE_TOOL
            | LIST_CEREMONY_INSTANCES_TOOL
            | SEARCH_CEREMONY_INSTANCES_TOOL
            | REQUEST_CEREMONY_INTERVENTION_TOOL
            | RESPOND_TO_CEREMONY_INTERVENTION_TOOL
            | CLOSE_CEREMONY_INTERVENTION_TOOL
            | COLLECT_CEREMONY_EVIDENCE_TOOL
            | ASSERT_CEREMONY_REASON_TOOL
            | DESIGN_CEREMONY_TOOL
            | VALIDATE_CEREMONY_DRAFT_TOOL
            | EXPLAIN_CEREMONY_DRAFT_TOOL
            | PUBLISH_CEREMONY_DEFINITION_TOOL
            | START_PUBLISHED_CEREMONY_TOOL
            | DIFF_CEREMONY_DEFINITIONS_TOOL
            | BIND_CEREMONY_PARTICIPANTS_TOOL
            | READ_CEREMONY_EVENTS_TOOL
            | STREAM_CEREMONY_TOOL
            | PULL_CEREMONY_EVENTS_TOOL
            | VERIFY_CEREMONY_JOURNAL_TOOL
            | GET_CEREMONY_TRANSCRIPT_TOOL
            | GENERATE_CEREMONY_REPORT_TOOL
            | GET_STATUS_TOOL
            | GET_METRICS_TOOL
    )
}
